### ISSUE TITLE
Problem: missing sed that work on both OSX and linux

### ISSUE THREAD

**Issue by allthatjazzleo** [crypto-com/chain-docs#19]
https://chain.crypto.com/docs/getting-started/croeseid-testnet.html#step-2-2-configurate-chain-maind
currently, it can only work on OSX not linux and can only run one time(not idempotent)
Also, should change `seeds` instead of `persistent_peers`

Suggestion
```bash
$ sed -i.bak -E 's#^(seeds[[:space:]]+=[[:space:]]+).*$#\1"66a557b8feef403805eb68e6e3249f3148d1a3f2@54.169.58.229:26656,3246d15d34802ca6ade7f51f5a26785c923fb385@54.179.111.207:26656,69c2fbab6b4f58b6cf1f79f8b1f670c7805e3f43@18.141.107.57:26656"# ; s#^(create_empty_blocks_interval[[:space:]]+=[[:space:]]+).*$#\1"5s"#' ~/.chain-maind/config/config.toml
```

**Comment by lezzokafka** [comment]
Has been resolved by #20 

https://chain.crypto.com/docs/getting-started/croeseid-testnet.html#step-2-2-configurate-chain-maind
