### ISSUE TITLE
Problem: Missing documentation for state sync

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain-docs#4]
> State sync rapidly bootstraps a new node by discovering, fetching, and restoring a state machine snapshot from peers instead of fetching and replaying historical blocks

state sync option has to be enabled in `config.toml`. We can experiment and document the feature and see what's the speed improvement of it.

**Comment by lezzokafka** [comment]
https://github.com/crypto-com/chain-main/releases/tag/v0.7.0-rc1

**Comment by lezzokafka** [comment]
-  Warning with "Caution" - tab  -- the data will be "incomplete" etc
- Chang config.toml `enable = false` => `enable = true`
- Set RPC servers in 
- Get trusted block hash from https://testnet-croeseid-1.crypto.com:26657/block
```
LASTEST_HEIGHT=$(curl -s https://testnet-croeseid-1.crypto.com:26657/block | jq -r .result.block.header.height)
BLOCK_HEIGHT=$((LASTEST_HEIGHT - 1000))
TRUST_HASH=$(curl -s "https://testnet-croeseid-1.crypto.com:26657/block?height=$BLOCK_HEIGHT" | jq -r .result.block_id.hash)
sed -i "s/^\(trust_height\s*=\s*\).*\$/\1$BLOCK_HEIGHT/" ~/.chain-maind/config/config.toml
sed -i "s/^\(trust_hash\s*=\s*\).*\$/\1\"$TRUST_HASH\"/" ~/.chain-maind/config/config.toml
```
Thanks @allthatjazzleo  👍

**Comment by allthatjazzleo** [comment]
working on it
