### ISSUE TITLE
Problem: No un-jail instruction in the testnet docs 

### ISSUE THREAD

**Issue by lezzokafka** [crypto-com/chain-docs#42]
It is provided in the [chain-maind cli page](https://chain.crypto.com/docs/wallets/cli.html#tx-slashing-unjail-unjailing-a-validator) but not included in the testnet docs.

**Comment by crypto-matto** [comment]
I think we just need to mention some easier & common operations like transfer, staking & query balance is enough for the testnet doc guide. We may add a reminder and redirect people to chain-maind cli page, like "If you wish to perform more advance operations, please refer ..."
