### ISSUE TITLE
Problem: Outdated Devnet guide with pystarport

### ISSUE THREAD

**Issue by lezzokafka** [crypto-com/chain-docs#47]
Need to be updated after the changes in [chain-main#260](https://github.com/crypto-com/chain-main/commit/9480b73b97c0c663d772a4bce4354b9e986e279d).

**Comment by lezzokafka** [comment]
```
cd pystarport
pip3 install .

cd .. 
pystarport serve --config examples/devnet.yaml
```
The data/config is now located at `data/<chain-id>` and also the mnemonic (`account.json`)

**Comment by yihuang** [comment]
i think you can
```
pip3 install pystarport 
pystarport serve ...
```
To save two lines
