### ISSUE TITLE
Problem: keyring-backend is not explained 

### ISSUE THREAD

**Issue by lezzokafka** [crypto-com/chain-docs#63]
**Suggestion**:  
Add further details to [#Keys managements](https://chain.crypto.com/docs/wallets/cli.html#keys-managements-chain-maind-keys). While we have been using `keyring-backend test` for most of the examples.

Useful ref: 
https://docs.cosmos.network/master/run-node/keyring.html.

**Comment by crypto-matto** [comment]
Resolved in #69
