### ISSUE TITLE
Problem: `check-validator-up.sh` does not work for more then 100 active validators 

### ISSUE THREAD

**Issue by lezzokafka** [crypto-com/chain-docs#78]
```bash
ADDRESS=$(curl --max-time 10 -sSL "${TENDERMINT_URL}/validators?per_page=300" | jq -r --arg PUBKEY "${PUBKEY}" '.result.validators[] | select(.pub_key.value == $PUBKEY) | .address')
```
See [link](https://github.com/crypto-com/chain-docs/blob/5a8b8cf377a078042e02d8fb9ac8947dd0e03575/docs/getting-started/assets/signature_checking/check-validator-up.sh#L53). It would not cover the case for more than 100 validators as the maximum result per page is 100.

**Comment by allthatjazzleo** [comment]
working on it
